### ISSUE TITLE
Gallery: Pictures overlapping with navigation bar in mobile mode

### ISSUE THREAD

**Issue by Emily-Kang77** [webimpactuw/snowy-village#26]
**Why:**
 In mobile mode, the gallery pictures overlap with the navigation bar. I think the issue is in GalleryGrid.tsx. There's one place where `absolute inset-0`. We probably shouldn't use `absolute` to make things fully responsive instead of fixing certain items on the page.

**Extra notes:**
Code quality: Consider renaming the App function to Gallery because that's confusing to have App in Gallery.tsx and App in App.tsx. I don't think the name is what's causing this bug though.

![image](https://github.com/webimpactuw/snowy-village/assets/109045956/7bdff529-6d69-448b-bb2e-fd5871364cee)

But the Menu page does respect the navigation bar boundaries, as seen in this picture.

![image](https://github.com/webimpactuw/snowy-village/assets/109045956/b9036465-a9d7-44c2-b0e7-c95bda546128)

**Comment by lezhimiffyliu** [comment]
Thank you for pointing out. I think the absolute inset-0 is not causing the problem, instead, I have applied z-index on the navbar, which solved this issue. However, I don't know if it's causing other problems so I haven't merge to main yet just to make sure. If everything else is fine with this change I will do so.

**Comment by Emily-Kang77** [comment]
Oh thanks. Can you mention the issue in your description so we can directly see the commit? Or in this issue mention the commit like this: https://github.com/webimpactuw/snowy-village/commit/4f34c85c9729c0d1393e70a6e446bc6e019cbd40

I think z-index makes sense on the navbar. Feel free to commit and make a pull request so we can download your code and make sure the pages look good. 

Does the ice cream picture start under the navbar or is it now covered by the navbar in mobile mode?
